// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALGp5a447f71e1EnIneLFLyokvS0ltiMc',
    appId: '1:1026130790730:web:ee4142122aab938f6559b3',
    messagingSenderId: '1026130790730',
    projectId: 'flutter-ci-todo-1234',
    authDomain: 'flutter-ci-todo-1234.firebaseapp.com',
    storageBucket: 'flutter-ci-todo-1234.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf4np_kwZvgIW51aLYQdIblYy1uSMZ1Zg',
    appId: '1:1026130790730:android:661b9775adcdf0ec6559b3',
    messagingSenderId: '1026130790730',
    projectId: 'flutter-ci-todo-1234',
    storageBucket: 'flutter-ci-todo-1234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCceC2tjym6MDwFqiKBKFvKNcO-B6JmVL0',
    appId: '1:1026130790730:ios:8d9f51e855dd75c56559b3',
    messagingSenderId: '1026130790730',
    projectId: 'flutter-ci-todo-1234',
    storageBucket: 'flutter-ci-todo-1234.firebasestorage.app',
    iosBundleId: 'com.example.flutterCiTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCceC2tjym6MDwFqiKBKFvKNcO-B6JmVL0',
    appId: '1:1026130790730:ios:8d9f51e855dd75c56559b3',
    messagingSenderId: '1026130790730',
    projectId: 'flutter-ci-todo-1234',
    storageBucket: 'flutter-ci-todo-1234.firebasestorage.app',
    iosBundleId: 'com.example.flutterCiTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALGp5a447f71e1EnIneLFLyokvS0ltiMc',
    appId: '1:1026130790730:web:cb8709e9d401775a6559b3',
    messagingSenderId: '1026130790730',
    projectId: 'flutter-ci-todo-1234',
    authDomain: 'flutter-ci-todo-1234.firebaseapp.com',
    storageBucket: 'flutter-ci-todo-1234.firebasestorage.app',
  );
}
